# Global settings
regtest=1

# Regtest-specific settings
[regtest]
datadir=D:\bitcoin\btc-node1
server=1
rpcuser=kazuya
rpcpassword=kusama
rpcport=18443
port=18444
listen=1
fallbackfee=0.00001

# mining configuration
address=bcrt1qsaeer4a4uw445eeethryedutp95jl3nwuulmmu
interval=5